org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.8
loader_version=0.19.3
loom_version=1.10.5
fabric_api_version=0.136.1+1.21.8
cloth_config_version=19.0.147
java_version=21

mod_version=1.3.0+mc1.21.8
maven_group=org.dawnteam
archives_base_name=DawnGuiReader
